export default {
	SET_POST_TYPE: 'SET_POST_TYPE',
	UPDATE_POST: 'UPDATE_POST',
	CLEAR_POST: 'CLEAR_POST',

	SUBMIT_POST_REQUEST: 'SUBMIT_POST_REQUEST',
	SUBMIT_POST_SUCCESS: 'SUBMIT_POST_SUCCESS',
	SUBMIT_POST_FAIL: 'SUBMIT_POST_FAIL'
}