export default {
	RECENT_VLOG_REQUEST: 'RECENT_VLOG_REQUEST',
	RECENT_VLOG_SUCCESS: 'RECENT_VLOG_SUCCESS',
	RECENT_VLOG_FAIL: 'RECENT_VLOG_FAIL',

	POST_BY_TITLE_REQUEST: 'POST_BY_TITLE_REQUEST',
	POST_BY_TITLE_SUCCESS: 'POST_BY_TITLE_SUCCESS',
	POST_BY_TITLE_FAIL: 'POST_BY_TITLE_FAIL'
}